"""A finding that blames the site for one template's fault.

Promised on the how-to hub. Sourced from the registered check `social.twitter`,
whose docstring records the miss this page is built on: it told a public library
site it had no share cards while that site's most-shared template carried
complete card markup, and the fix said to add the card type without saying
where.

⚠️ THE EXAMPLE SITE IS NOT NAMED. The deploy's third-party gate refuses pages
naming sites we measured without asking, and that rule is right.

Complements /learn/audit-tool-accuracy/ (how to tell whether a tool is lying)
with the narrower, more common case: the tool is telling the truth and counting
the wrong unit.

No numeric literals.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from render import render  # noqa: E402


def template_findings() -> Path:
    body = """
<p class="lede">Most audit findings are a count: some number of your pages are missing
something. The count is usually correct and the unit is usually wrong, because the thing being
counted was not decided page by page. It was decided once, in a template, and the count is the
number of pages that template produced.</p>

<h2>What this looks like in practice</h2>

<p>A tool reports that a site has no share cards. Somebody goes to add them, and finds the most
important pages on the site — the ones people actually share — already have complete card
markup. The pages without were a different template entirely: a listing, or an archive, or
something generated by a different part of the system.</p>

<p>That is a real case, from an audit this product ran. The count was accurate. The verdict was
not, and the advice — add the card type — did not say where, so the only way to act on it was to
go looking for pages that were already correct.</p>

<h2>Why the unit matters more than the number</h2>

<p>Almost every property an audit measures is set in a layout, a partial, a theme file or a
component. Titles, descriptions, canonical tags, card markup, structured data, heading order.
One edit, applied to every page that uses it.</p>

<p>So findings cluster by template, not by page, and a count without a location is close to
useless in both directions: it overstates the work when one edit fixes everything, and it
understates the danger when a template you thought was fine turns out to produce a third of the
site.</p>

<p><strong>A majority is not a site.</strong> "Most of your pages" and "your site" are different
claims, and the gap between them is exactly where the useful information lives.</p>

<h2>What to do with a finding like this</h2>

<p><strong>Ask which template the affected pages share, before doing anything.</strong> Sort the
affected URLs by their path and the answer usually falls out immediately: everything under one
section, or every page of one kind. That grouping is the actual finding.</p>

<p><strong>Then check one page that was not flagged.</strong> If a page of the same kind is
correct, you are looking at a template that was fixed once and not everywhere — a different
problem from one that was never done.</p>

<p><strong>Fix it where it was decided.</strong> If the answer is one file, the count was never
the size of the job.</p>

<h2>What a tool should do, and what it cannot</h2>

<p>It should say <em>every</em> page only when it is every page, give a proportion otherwise,
and name the URLs so the grouping is visible without exporting anything. A finding that reports
a majority in the voice of a totality is making a claim it did not measure.</p>

<p>It cannot tell you which template is which. A crawler sees URLs and HTML; it does not have
your theme, your components, or the knowledge that two paths come from the same partial. The
grouping it can offer is a hint you confirm, not an answer — and a tool that claimed otherwise
would be guessing at your CMS.</p>

<p>This one got it wrong in the direction described above, and the check now distinguishes
"every page" from "most of them". A page citing a check is worth more for saying when the check
was wrong than for implying it never is.</p>

<h2>The narrower question about share cards</h2>

<p>Cards are worth having, and they are worth raising only once the basic sharing markup is
already in place — a site with neither has one problem, not two, and being told twice is noise
rather than thoroughness.</p>

<p>The broader question of how to tell whether a tool is lying to you is
<a href="/learn/audit-tool-accuracy/">a separate piece</a>.</p>
"""
    return render(
        cat="how-to", slug="read-findings-that-blame-the-whole-site",
        title="When an audit blames the site for one template",
        desc=("Most findings count pages when the fault lives in a template. How to read an "
              "audit of your site by the unit that was decided, not the number."),
        h1="When an audit blames the site for one template",
        crumb='<a href="/">Docket</a> / <a href="/how-to/">Fix it</a> / template findings',
        body=body,
        faq=[
            ("Why do audit findings overstate the work?",
             "Because they count pages, and most of what they measure was decided once in a "
             "template. The count is the number of pages that template produced, so one edit "
             "often fixes all of them."),
            ("How do I tell whether a finding is a template problem?",
             "Sort the affected URLs by path. If they all sit under one section, or are all "
             "pages of one kind, that grouping is the real finding. Then check a page that was "
             "not flagged — if it is the same kind and correct, a template was fixed once and "
             "not everywhere."),
            ("Is 'most of your pages' the same as 'your site'?",
             "No, and the gap is where the useful information lives. A finding that reports a "
             "majority in the voice of a totality is making a claim it did not measure."),
            ("Can a crawler work out which template a page came from?",
             "Not reliably. It sees URLs and HTML, not your theme or components. Any grouping "
             "it offers is a hint you confirm rather than an answer, and a tool claiming "
             "otherwise is guessing at your CMS."),
            ("Do I need share cards if I already have basic sharing markup?",
             "They are worth having, and worth raising only once the basic markup is in place. "
             "A site with neither has one problem, not two, and being told twice is noise "
             "rather than thoroughness."),
        ],
    )


if __name__ == "__main__":
    print(template_findings())
