#!/usr/bin/env bash
# Build, gate, and publish scoutseo.app.
#
# Deploys by pushing site/ to the `gh-pages` branch, which GitHub Pages serves
# directly. This replaced an Actions workflow that failed three times in a row
# with "The job was not acquired by Runner of type hosted" — runner starvation
# on GitHub's side, unrelated to anything in this repo, and each failure sat in
# the queue for 15+ minutes before giving up. `timeout-minutes` does not help:
# it bounds execution, not queue wait.
#
# A hosted runner was never needed here. The site is static, and the build and
# the quality gate both run locally in under a second. The workflow remains in
# .github/workflows/ as a fallback and no longer sits on the critical path.
set -euo pipefail

cd "$(dirname "$0")/.."
PY="${PYTHON:-python3}"

echo "==> build"
"$PY" scripts/build.py >/dev/null

echo "==> derived-number gate"
# The Index published 30% over a 26% dataset because a correction updated the
# prose and not the stored aggregate. This refuses to ship a measurement that
# was typed rather than derived, which is the only version of that bug that
# cannot be caught by reading.
"$PY" scripts/verify_numbers.py

echo "==> quality gate"
# Runs against the built HTML. A failure here must stop the deploy: this is the
# only thing standing between a bad edit and the live site.
"$PY" scripts/lint.py site

echo "==> contact gate"
# The footer advertised hello@scoutseo.app on all 25 pages and the domain has
# no MX record, so every message anyone sent bounced to them silently. A dead
# mailbox is worse than a broken link: a 404 tells the visitor it failed. This
# resolves every mailto domain and requests every advertised contact URL.
"$PY" scripts/verify_contact.py

echo "==> link-graph gate"
# site/_data/link-equity.json is a measurement of this site, published through
# facts.py by /learn/internal-link-equity/. It was generated by a command that
# existed only in a terminal, so nothing could tell whether it still described
# the site. This recomputes the graph and fails if the dataset has drifted —
# the same fix the article itself argues for, applied to the article's own data.
"$PY" scripts/verify_link_graph.py

echo "==> visual gate"
# lint.py reads HTML and counts braces. Neither can answer "what colour is this
# link, finally" — and two stray braces once silently deleted the rule that
# coloured every link in every article, and the rule that drew the homepage
# hero. This renders the built pages in WebKit and asserts computed values.
#
# It self-tests first: both historical bugs are injected into throwaway copies
# and the gate must fail on each. A gate that has never been seen to fail is
# not evidence of anything, and both of those bugs shipped past a green build.
"$PY" scripts/visual_check.py --self-test
"$PY" scripts/visual_check.py

if [ -f scripts/publish_knowledge.py ]; then
  echo "==> knowledge feed gate"
  "$PY" scripts/publish_knowledge.py
fi

# CNAME lives in site/ so it survives into the deployed branch root. Without it
# GitHub drops the custom domain on the next deploy and scoutseo.app 404s.
if [ ! -f site/CNAME ]; then
  echo "FAIL — site/CNAME is missing; deploying would drop the custom domain" >&2
  exit 1
fi

if [ -n "$(git status --porcelain site)" ]; then
  echo "==> committing rebuilt site"
  git add site
  git commit -qm "${1:-site: rebuild}"
fi

echo "==> push main"
git push -q origin main

echo "==> publish site/ to gh-pages"
git branch -D gh-pages-tmp >/dev/null 2>&1 || true
git subtree split --prefix site -b gh-pages-tmp >/dev/null
git push -qf origin gh-pages-tmp:gh-pages
git branch -D gh-pages-tmp >/dev/null

echo "==> done — https://scoutseo.app (propagation takes a minute)"
