#!/usr/bin/env bash
# Build, gate, and publish docketseo.app.
#
# Deploys by pushing site/ to the `gh-pages` branch, which GitHub Pages serves
# directly. This replaced an Actions workflow that failed three times in a row
# with "The job was not acquired by Runner of type hosted" — runner starvation
# on GitHub's side, unrelated to anything in this repo, and each failure sat in
# the queue for 15+ minutes before giving up. `timeout-minutes` does not help:
# it bounds execution, not queue wait.
#
# A hosted runner was never needed here. The site is static, and the build and
# the quality gate both run locally in under a second. The workflow remains in
# .github/workflows/ as a fallback and no longer sits on the critical path.
set -euo pipefail

cd "$(dirname "$0")/.."
PY="${PYTHON:-python3}"

echo "==> build"
"$PY" scripts/build.py >/dev/null

echo "==> derived-number gate"
# The Index published 30% over a 26% dataset because a correction updated the
# prose and not the stored aggregate. This refuses to ship a measurement that
# was typed rather than derived, which is the only version of that bug that
# cannot be caught by reading.
"$PY" scripts/verify_numbers.py

echo "==> derived-data freshness gate"
# verify_numbers.py refuses a number that was typed. It cannot see a number
# that was derived from a dataset nobody rebuilt: the prose and the data agree
# with each other and both are stale. /learn/audit-tool-accuracy/ shipped
# "17 of the 35 test files" for six days against a repo with 74 of 145.
"$PY" scripts/verify_derived_data.py

echo "==> quality gate"
# Runs against the built HTML. A failure here must stop the deploy: this is the
# only thing standing between a bad edit and the live site.
"$PY" scripts/lint.py site

echo "==> contact gate"
# The footer advertised hello@scoutseo.app on all 25 pages and the domain has
# no MX record, so every message anyone sent bounced to them silently. A dead
# mailbox is worse than a broken link: a 404 tells the visitor it failed. This
# resolves every mailto domain and requests every advertised contact URL.
"$PY" scripts/verify_contact.py

echo "==> competitive-claim gate"
# The homepage said "Four things crawler tools ignore" — unsourced, undated, on
# the page with more traffic than every /vs/ page combined, and wrong on its
# sharpest point: Screaming Frog's user guide describes switching user-agent and
# following that agent's robots.txt directives, which is the AI-crawler question
# we said it ignored. Every comparison page quotes its source; this makes the
# rest of the site meet the same standard.
"$PY" scripts/verify_competitive_claims.py

echo "==> brand asset gate"
# Three different marks across four files, found by opening them: the favicon
# was the desktop app's indigo, and icon.png and og.png were still the orange
# Scout diamond from before the rename — og.png being the picture every shared
# link of this site had been showing. lint.py reads HTML, visual_check.py
# asserts computed CSS and verify_live.py checks files are served; a served
# file that is the wrong picture passes all three, because nothing read a
# pixel. This re-renders all four from the --brand token and compares.
"$PY" scripts/render_brand_assets.py --check || exit 1

echo "==> third-party gate"
# This site published a page-by-page audit of a named delicatessen — the domain,
# 33 page URLs, their titles and per-page risk scores — at a public URL and in
# a public repo. Nobody asked us to. The result was flattering, which is not a
# defence: it was flattering that week, and the consent was never there.
#
# "Do not name private parties who never asked to be audited" was a rule in a
# prompt, which means it held for as long as someone remembered it. Now it fails
# a build.
"$PY" scripts/verify_no_named_third_parties.py

echo "==> monitoring-caveat gate"
"$PY" scripts/verify_monitoring_caveat.py

echo "==> action gate"
"$PY" scripts/verify_action.py

echo "==> link-graph gate"
# site/_data/link-equity.json is a measurement of this site, published through
# facts.py by /learn/internal-link-equity/. It was generated by a command that
# existed only in a terminal, so nothing could tell whether it still described
# the site. This recomputes the graph and fails if the dataset has drifted —
# the same fix the article itself argues for, applied to the article's own data.
"$PY" scripts/verify_link_graph.py

echo "==> visual gate"
# lint.py reads HTML and counts braces. Neither can answer "what colour is this
# link, finally" — and two stray braces once silently deleted the rule that
# coloured every link in every article, and the rule that drew the homepage
# hero. This renders the built pages in WebKit and asserts computed values.
#
# It self-tests first: both historical bugs are injected into throwaway copies
# and the gate must fail on each. A gate that has never been seen to fail is
# not evidence of anything, and both of those bugs shipped past a green build.
"$PY" scripts/visual_check.py --self-test
"$PY" scripts/visual_check.py

echo "==> updater gate"
"$PY" scripts/verify_updater.py || exit 1

if [ -f scripts/publish_knowledge.py ]; then
  echo "==> knowledge feed gate"
  "$PY" scripts/publish_knowledge.py
fi

# CNAME lives in site/ so it survives into the deployed branch root. Without it
# GitHub drops the custom domain on the next deploy and docketseo.app 404s.
if [ ! -f site/CNAME ]; then
  echo "FAIL — site/CNAME is missing; deploying would drop the custom domain" >&2
  exit 1
fi

if [ -n "$(git status --porcelain site)" ]; then
  echo "==> committing rebuilt site"
  git add site
  git commit -qm "${1:-site: rebuild}"
fi

echo "==> push main"
git push -q origin main

echo "==> publish site/ to gh-pages"
git branch -D gh-pages-tmp >/dev/null 2>&1 || true
git subtree split --prefix site -b gh-pages-tmp >/dev/null
git push -qf origin gh-pages-tmp:gh-pages
git branch -D gh-pages-tmp >/dev/null

echo "==> done — https://docketseo.app (propagation takes a minute)"
echo
echo "    verify what the CDN is actually serving, once it has propagated:"
echo "      python3 scripts/verify_live.py"
