#!/usr/bin/env python3
"""Recompute the internal link graph and require the stored dataset to match.

`/learn/internal-link-equity/` publishes its figures through facts.py, which
reads data/link-equity.json. That file is a measurement of this site, and
it was generated by a command that lived in a terminal and nowhere else — so
the only way to know whether it still described the site was to reconstruct
what it had counted from the numbers it left behind.

That is the same shape as the bug the article is about. A measurement nobody
can re-run is a number typed into prose with extra steps: it goes stale in
silence, and the page keeps asserting it.

The methodology, recovered and now written down:

  * A node is a directory containing index.html, addressed by its trailing-slash
    path. `/` for the root.
  * An edge is a *unique* (source, target) pair. Chrome counts — the nav is a
    real path to a page and the article's argument is about total inbound
    routes — but twenty hrefs from one page to another are one route, not
    twenty. Counting raw hrefs gives 570 where the truth is 363.
  * Self-links do not count.

Usage:  python3 scripts/verify_link_graph.py [--write]
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
DATASET = ROOT / "data" / "link-equity.json"

HREF = re.compile(r'href="(/[^"#?]*)"')


def path_of(page: Path) -> str:
    rel = str(page.parent.relative_to(SITE))
    return "/" if rel == "." else f"/{rel}/"


def measure() -> tuple[dict, dict[str, set[str]]]:
    """The graph, and any internal href that points at nothing.

    Both come from the same walk. An earlier version filtered non-resolving
    hrefs out silently on its way to counting edges, which is how /about/ went
    live linking to /learn/entity-schema/ — a page that has never existed, at a
    guessed path, past every gate. Docket found it on the deployed site.
    """
    pages = sorted(SITE.rglob("index.html"))
    paths = {path_of(p) for p in pages}
    pairs: set[tuple[str, str]] = set()
    broken: dict[str, set[str]] = {}
    for page in pages:
        src = path_of(page)
        for href in HREF.findall(page.read_text()):
            target = href if href.endswith("/") else href + "/"
            if target not in paths:
                # A direct file reference (/sitemap.xml, /robots.txt) is a link
                # to a thing on disk rather than to a page in the graph.
                if not (SITE / href.lstrip("/")).exists():
                    broken.setdefault(href, set()).add(src)
                continue
            if target != src:
                pairs.add((src, target))

    inlinks = {p: 0 for p in paths}
    for _, target in pairs:
        inlinks[target] += 1

    total = len(pairs)
    nodes = []
    for path in sorted(paths):
        n = inlinks[path]
        nodes.append({"path": path, "inlinks": n,
                      "share_pct": round(100 * n / total, 2) if total else 0.0})
    average = round(sum(x["share_pct"] for x in nodes) / len(nodes), 2)
    for node in nodes:
        node["index"] = round(node["share_pct"] / average, 2) if average else 0.0

    return ({"site": "docketseo.app", "pages": len(paths), "edges": total,
             "average_share_pct": average,
             "below_half": sum(1 for x in nodes if x["index"] < 0.5),
             "nodes": nodes}, broken)


def main() -> int:
    if not DATASET.exists():
        print(f"LINKS: {DATASET} is missing")
        return 1
    stored = json.loads(DATASET.read_text())
    live, broken = measure()

    if broken:
        print(f"LINKS: {len(broken)} internal link(s) point at nothing")
        for href, sources in sorted(broken.items()):
            print(f"  {href} <- {', '.join(sorted(sources)[:3])}")
        return 1

    problems = []
    for key in ("pages", "edges", "average_share_pct", "below_half"):
        if stored.get(key) != live[key]:
            problems.append(f"{key}: dataset says {stored.get(key)}, "
                            f"the site is {live[key]}")

    stored_nodes = {n["path"]: n["inlinks"] for n in stored.get("nodes", [])}
    live_nodes = {n["path"]: n["inlinks"] for n in live["nodes"]}
    for path in sorted(set(stored_nodes) | set(live_nodes)):
        a, b = stored_nodes.get(path), live_nodes.get(path)
        if a != b:
            problems.append(f"{path}: dataset says {a} inlinks, the site has {b}")

    if problems:
        print(f"LINKS: the stored graph no longer describes the site "
              f"({len(problems)} difference(s))")
        for p in problems[:12]:
            print(f"  {p}")
        if "--write" not in sys.argv:
            print("  re-run with --write --date YYYY-MM-DD once you have "
                  "confirmed the change is intended")
            return 1
        try:
            date = sys.argv[sys.argv.index("--date") + 1]
        except (ValueError, IndexError):
            print("  --write needs --date YYYY-MM-DD. The `measured` field is "
                  "what tells a reader how old the figure is; refreshing the "
                  "numbers and leaving the date is the stale-number bug with "
                  "extra steps.")
            return 1
        live["measured"] = date
        DATASET.write_text(json.dumps(live, indent=2) + "\n")
        print(f"  written: {live['pages']} pages, {live['edges']} routes, "
              f"measured {date}")
        return 0

    if "--write" in sys.argv:
        print("LINKS: already current, nothing to write")
    print(f"LINKS ok — {live['pages']} pages, {live['edges']} unique routes, "
          f"matches data/link-equity.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
